name: print hello world
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: |
       - echo 'Hello world'
       - ls -lrt
       - lscpu
      
    




