name: print hello world
on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - name: print hello world
      run: echo 'hello world'
    - name: check python version
      run: python --version
    - run: date
    - run: pip install boto3




